name: Build and Deploy Vue.js App

on:
  push:
    branches:
      - staging

env:
  VITE_API_URL: https://teraerpstaging-fuc8axegceeccqeg.canadacentral-01.azurewebsites.net/api

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      NODE_OPTIONS: "--max-old-space-size=1024"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable
        
      - name: set node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Memory
        run: free -h  

      - name: Build Vue App
        run: yarn build

      - name: Deploy to Server
        run: |
          sudo mkdir -p /var/www/vue-app/production
          sudo rsync -av --delete dist/ /var/www/vue-app/production/dist/

      - name: Reload Nginx
        run: sudo systemctl reload nginx
