name: Build and Deploy to Staging environment

on:
  push:
    branches:
      - staging
env:
  VITE_API_URL:  https://kosoorstagingapi.azurewebsites.net/api
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable
        
      - name: set node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Vue.js Project
        run: yarn build --mode staging

      - name: Copy Files to Web Server
        run: |
          sudo rm -rf /var/www/teraerp-admin-staging/html/*
          sudo cp -r dist/* /var/www/teraerp-admin-staging/html/
          
      - name: Reload Nginx
        run: sudo systemctl reload nginx
