name: Build and Deploy Vue.js App

on:
  push:
    branches:
      - testing

env:
  VITE_API_URL: https://teraerptesting-ffgxa9ejepc4bpfp.canadacentral-01.azurewebsites.net/api

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Vue App
        run: yarn build

      - name: Deploy to Server
        run: |
          sudo rm -rf /var/www/vue-app/testing/dist
          sudo mkdir -p /var/www/vue-app/testing/dist
          sudo cp -r dist/* /var/www/vue-app/testing/dist/

      - name: Reload Nginx
        run: sudo systemctl reload nginx
